name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os:
          - "macos-latest"
          - "ubuntu-latest"
          # - "windows-latest"  # TODO enable windoze, I don't want to figure out powershell downloading right meow
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Download test files
        run: scripts/download-test-files
      - name: Test
        run: cargo test
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Fmt
        run: cargo fmt
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy